In [1]:
import numpy as np

In [3]:
arr =  np.array([[1,2,3],[10,20,30]])
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

Indexing

In [7]:
print(arr[1,2])
print(arr[0,2])
print(arr[0,:])

30
3
[1 2 3]


Array Operations

In [8]:
arr1 = np.array([15,25,35])
arr2 = np.array([20,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1**2)
print(arr2**2)

[35 65 85]
[ -5 -15 -15]
[ 300 1000 1750]
[ 225  625 1225]
[ 400 1600 2500]


Comparison Operations

In [9]:
arr3 = np.array([3,10,2,6])
print(arr3>5)

[False  True False  True]


Universal Functions

In [14]:
np.sqrt([2,4,9])
np.exp([2,4,9])
np.sin([0,np.pi/2])

array([0., 1.])

Broadcasting

one array is 1D and 2nd array is 2D, then elements will 2D array will operaation on 1D array

In [15]:
arr4 = np.array([[1],[2],[3]])
arr5 = np.array([5,6,7])
print(arr5+arr4)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


Reshaping

In [18]:
arr6 = np.array([[1,2],[3,4],[5,6]])
arr6
print(arr6.reshape(2,3))

#Flattening : All the elements will be in single array
print(arr6.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
