Step 1 : Install Numpy

In [3]:
pip install numpy

Import Numpy

In [4]:
import numpy as np

Creating an array

In [5]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


Array Dimention

In [6]:
print(arr.ndim)

1


Shape of an Array

In [7]:
print(arr.shape)

(4,)


Size of an Array

In [8]:
print(arr.size)

4


DataType

In [9]:
print(arr.dtype)

int64


2-D Array

In [11]:
arr1 = np.array([[10,20],[30,40]])
print(arr1)

[[10 20]
 [30 40]]


Operations

In [12]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

2
(2, 2)
4
int64


Numpy Array using function

In [13]:
np.arange(1,20,2) #start from 1, end at 20 and step value iss 2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
np.arange(20,0,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [15]:
np.linspace(0,10,2)

array([ 0., 10.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])