Import Libraries and load dataset

In [3]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.svm import SVC

iris = datasets.load_iris()
X = iris.data
y = iris.target

Printing Data

In [4]:
X = X[:, :2] #using sepal leangth and sepal with

print("----------- Data Load and Prepared for Binary Classification ----------")
print("Shape of features (x): ", X.shape)
print("Shape of features (Y): ", y.shape)
print("\n")

----------- Data Load and Prepared for Binary Classification ----------
Shape of features (x):  (150, 2)
Shape of features (Y):  (150,)




Split data into training (80%) and testing (20%) sets

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

Feature Scaling

In [7]:
scaler = StandardScaler()
X_tran_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Print Scaler
print("----------- Feature Scaling ----------")
print("Data has been scaled to have a mean of 0 and a standard deviation of 1")
print("\n")

----------- Feature Scaling ----------
Data has been scaled to have a mean of 0 and a standard deviation of 1




Create and train the SVM model

In [8]:
# kernel = liner is used for creating a liner decision boundary
model = SVC(kernel="linear")
model.fit(X_tran_scaled, y_train)
print("----------- SVM Model Trained ----------")
print("\n")

----------- SVM Model Trained ----------




In [9]:
# Make prediction on test set
y_pred = model.predict(X_test_scaled)

In [10]:
#Evaluate the Model's performance
print("----------- Model Evaluation ----------")

#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("\n")

----------- Model Evaluation ----------
Confusion Matrix:
[[10  0  0]
 [ 0  5  5]
 [ 0  3  7]]




In [12]:
#Accuracy score
accuracy_score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy_score:.2f}")
print("\n")

Accuracy: 0.73




In [13]:
#Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("\n")

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.62      0.50      0.56        10
           2       0.58      0.70      0.64        10

    accuracy                           0.73        30
   macro avg       0.74      0.73      0.73        30
weighted avg       0.74      0.73      0.73        30



